spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_PATH}
    username: ${DB_USERNAME}
    password: ${DB_PW}
    hikari:
      maximum-pool-size: 4
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: etc
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENTID}
            clientSecret: ${GOOGLE_CLIENTSECRET}
            scope:
              - email
              - profile
logging:
  logback:
    rollingpolicy:
      max-file-size: 50MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    name: logs/pre-project-rainbow.log

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/open-api-3.0.1.json
    path: /docs/swagger

jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${ACCESS_EXPIRATION_MINUTES}
  refresh-token-expiration-minutes: ${REFRESH_EXPIRATION_MINUTES}

User:
  mail:
    admin: ${ADMIN_EMAIL}
    disable: ${DISABLE_USER}
##${ADMIN_EMAIL}
##${DISABLE_USER}