spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rainbow
    username: root
    password: 0711dayoung
    hikari:
      maximum-pool-size: 4
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: etc
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 512989187776-v3qd22qlicq0ijalmt20tj4kih03en60.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
logging:
  logback:
    rollingpolicy:
      max-file-size: 50MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    name: logs/pre-project-rainbow.log

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/open-api-3.0.1.json
    path: /docs/swagger

jwt:
  key:
    secret: thisIsTestScretKeythisIsTestScretKeythisIsTestScretKeythisIsTestScretKey
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 600

User:
  mail:
    admin: ADMIN@ADMIN.com
    disable: TEST@TESTTEST.com
##${ADMIN_EMAIL}
##${DISABLE_USER}