spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_PATH}
    username: ${DB_USERNAME}
    password: ${DB_PW}
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: etc
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 512989187776-v3qd22qlicq0ijalmt20tj4kih03en60.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
jwt:
  key:
    secret: thisIsTestScretKeythisIsTestScretKeythisIsTestScretKeythisIsTestScretKey
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 600

User:
  mail:
    admin: ADMIN@ADMIN.com
    disable: TEST@TESTTEST.com
##${ADMIN_EMAIL}
##${DISABLE_USER}

